 final List<Map<String, dynamic>> sampleData = [
    {
      "title": "John Doe",
      "age": 24,
      "email": "john.doe@email.com",
      "profileImage": "https://randomuser.me/api/portraits/men/1.jpg",
      "interests": ["Music", "Sports", "Travel"],
      "isPremiumUser": true,
    },
    {
      "title": "Jane Smith",
      "age": 30,
      "email": "jane.smith@email.com",
      "profileImage": "https://randomuser.me/api/portraits/women/2.jpg",
      "interests": ["Books", "Art", "Movies"],
      "isPremiumUser": false,
    },
    {
      "title": "Michael Johnson",
      "age": 28,
      "email": "michael.j@email.com",
      "profileImage": "https://randomuser.me/api/portraits/men/3.jpg",
      "interests": ["Cooking", "Cycling"],
      "isPremiumUser": true,
    },
    {
      "title": "Emily Davis",
      "age": 22,
      "email": "emily.davis@email.com",
      "profileImage": "https://randomuser.me/api/portraits/women/3.jpg",
      "interests": ["Photography", "Fitness", "Travel"],
      "isPremiumUser": false,
    },
    {
      "title": "Chris Lee",
      "age": 35,
      "email": "chris.lee@email.com",
      "profileImage": "https://randomuser.me/api/portraits/men/4.jpg",
      "interests": ["Gaming", "Technology"],
      "isPremiumUser": false,
    },
    {
      "title": "Sophia Turner",
      "age": 27,
      "email": "sophia.turner@email.com",
      "profileImage": "https://randomuser.me/api/portraits/women/4.jpg",
      "interests": ["Yoga", "Cooking", "Reading"],
      "isPremiumUser": true,
    },
    {
      "title": "David Martinez",
      "age": 31,
      "email": "david.martinez@email.com",
      "profileImage": "https://randomuser.me/api/portraits/men/5.jpg",
      "interests": ["Fitness", "Photography", "Travel"],
      "isPremiumUser": true,
    },
    {
      "title": "Laura Wilson",
      "age": 29,
      "email": "laura.wilson@email.com",
      "profileImage": "https://randomuser.me/api/portraits/women/5.jpg",
      "interests": ["Art", "Movies", "Hiking"],
      "isPremiumUser": false,
    }
  ];
